
name: Linting

on:
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Black Check
        uses: psf/black@stable
        with:
          src: "./hackathon"
          version: "22.10.0"

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install isort
        run: |
          pip install isort==5.10.1

      - name: run isort
        run: |
          isort --check-only --quiet apax_nodes

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install flake8
        run: |
          pip install flake8==5.0.4

      - name: run flake8
        run: |
          flake8 apax_nodes --count --show-source --statistics
